// Code generated by Kitex v0.4.4. DO NOT EDIT.

package favoriteservice

import (
	"context"
	favorite "douyin/kitex_gen/favorite"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return favoriteServiceServiceInfo
}

var favoriteServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "FavoriteService"
	handlerType := (*favorite.FavoriteService)(nil)
	methods := map[string]kitex.MethodInfo{
		"FavoriteVideo":   kitex.NewMethodInfo(favoriteVideoHandler, newFavoriteServiceFavoriteVideoArgs, newFavoriteServiceFavoriteVideoResult, false),
		"GetFavoriteList": kitex.NewMethodInfo(getFavoriteListHandler, newFavoriteServiceGetFavoriteListArgs, newFavoriteServiceGetFavoriteListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "favorite",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func favoriteVideoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceFavoriteVideoArgs)
	realResult := result.(*favorite.FavoriteServiceFavoriteVideoResult)
	success, err := handler.(favorite.FavoriteService).FavoriteVideo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteServiceFavoriteVideoArgs() interface{} {
	return favorite.NewFavoriteServiceFavoriteVideoArgs()
}

func newFavoriteServiceFavoriteVideoResult() interface{} {
	return favorite.NewFavoriteServiceFavoriteVideoResult()
}

func getFavoriteListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceGetFavoriteListArgs)
	realResult := result.(*favorite.FavoriteServiceGetFavoriteListResult)
	success, err := handler.(favorite.FavoriteService).GetFavoriteList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteServiceGetFavoriteListArgs() interface{} {
	return favorite.NewFavoriteServiceGetFavoriteListArgs()
}

func newFavoriteServiceGetFavoriteListResult() interface{} {
	return favorite.NewFavoriteServiceGetFavoriteListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) FavoriteVideo(ctx context.Context, req *favorite.DouyinFavoriteActionRequest) (r *favorite.DouyinFavoriteActionResponse, err error) {
	var _args favorite.FavoriteServiceFavoriteVideoArgs
	_args.Req = req
	var _result favorite.FavoriteServiceFavoriteVideoResult
	if err = p.c.Call(ctx, "FavoriteVideo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFavoriteList(ctx context.Context, req *favorite.DouyinFavoriteListRequest) (r *favorite.DouyinFavoriteListResponse, err error) {
	var _args favorite.FavoriteServiceGetFavoriteListArgs
	_args.Req = req
	var _result favorite.FavoriteServiceGetFavoriteListResult
	if err = p.c.Call(ctx, "GetFavoriteList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
