// Code generated by hertz generator.

package main

import (
	"douyin/cmd/api/biz/rpc"
	"douyin/pkg/initialize"
)

func Init() {
	initialize.Viper()
	rpc.Init()
	initialize.Hertz()
}

func main() {
	Init()
}
