init_api:
	hz new -module douyin/cmd/api --idl=../../idl/api.thrift --thrift-plugins=validator # 在 cmd/api 目录下执行，然后删去 go.mod

update_api:
	hz update --idl=../../idl/api.thrift --thrift-plugins=validator # 在 cmd/api 目录下执行